### PR TITLE
Lm01/solution

### PR DESCRIPTION
**Pull request by tvcrawley**
Updated from solution branch and added answers on the absolute/relative paths section.

### CODE REVIEW

**Comment by jrhorn424** [comment]
@tvlangley Am I correct in concluding that you based this PR on @MicFin's unmerged solution from 016?

**Comment by tvcrawley** [comment]
@jrhorn424 It's based off the current solution branch

**Comment by jrhorn424** [comment]
@tvlangley Thanks! I had a confuse.

**Review by jrhorn424 — COMMENTED** [review]
Worked with @tvlangley to squash this branch before creating the new solution. Prior to squashing:

```
~/teaching/wdi/boston/unix-cli-diagnostic lm01/solution  
❯ git rev-list --left-right --count master...lm01/solution
1       4
```

Now, `solution` will be one ahead and one behind `master`.

**Pull request closed without merging**
