### PR TITLE
Submit diagnostic number 2 for Alex Kradin

### PR DESCRIPTION
**Pull request by akradin**
Navigate using the command line
Fork and clone using git
Answer questions

### CODE REVIEW

**Comment by neugierige** [comment]
4/5. Were you able to create the rhyme.txt file with command line? Let us know if you need help.

**Comment by akradin** [comment]
Yup, did it not get pushed? I may need help troubleshooting out why it didn’t get pushed.

**Comment by neugierige** [comment]
No, your commit only showed 1 changed file. This is something you can check with "git status." Maybe you didn't add it when you were committing? Give it another shot and see if you can push it.

**Comment by akradin** [comment]
Okay, pushed, should I create another pull request?

**Pull request closed without merging**
